/**
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
 * the MIT License. See LICENSE in the project root for license information.
 * <autogenerated> This file was generated using AutoRest. </autogenerated>
 */

package com.microsoft.socialplus.autorest.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Request to post (create) linked account.
 */
public class PostLinkedAccountRequest {
    /**
     * Gets or sets a session token.
     */
    @JsonProperty(required = true)
    private String sessionToken;

    /**
     * Get the sessionToken value.
     *
     * @return the sessionToken value
     */
    public String getSessionToken() {
        return this.sessionToken;
    }

    /**
     * Set the sessionToken value.
     *
     * @param sessionToken the sessionToken value to set
     */
    public void setSessionToken(String sessionToken) {
        this.sessionToken = sessionToken;
    }

}
